remote_input_directory: 'gs://mockcustomer-data-bucket/input'
remote_output_directory: 'gs://mockcustomer-data-bucket/output'
remote_repo_directory: 'gs://pypi_repo'
remote_custom_code_directory: 'gs://mockcustomer-data-bucket/sample_code'
remote_log_directory: 'gs://mockcustomer-data-bucket/logs/codebox'
input_directory: '/root/input'
output_directory: '/root/output'
custom_code_directory: '/root/custom_code'
repo_directory: '/root/repo'
log_directory: '/root/logs'
run_mode: 'process'