FROM python:3.7-buster
WORKDIR /root


# Mkdirs + Install Google Cloud SDK + client libraries
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && \
    apt-get update -y && \
    apt-get install google-cloud-sdk -y && \
    pip install google-cloud-storage==1.42.3 && \
    pip install pyyaml==5.4.1 && \
    mkdir /root/input && \
    mkdir /root/output && \
    mkdir /root/custom_code && \
    mkdir /root/repo && \
    mkdir /root/logs

# Path configuration
ENV PATH $PATH:/root/tools/google-cloud-sdk/bin

# Copies necessary code
COPY utils.py /root/codebox/utils.py
COPY codebox.py /root/codebox/codebox.py

# Sets up the entry point to invoke the trainer.
ENTRYPOINT ["python3", "/root/codebox/codebox.py"]